### PR TITLE
Added support of `containingAllOf`

### PR DESCRIPTION
**Pull request by GaneshSPatil**
`containingAllOf` helps to assert whether a subArray is a subset of the actualArray or not.

Example:
```
var numbers = [1, 2, 3];

assert.that(numbers).is.containingAllOf([1]);
assert.that(numbers).is.containingAllOf([2, 3]);
assert.that(numbers).is.containingAllOf([1, 2, 3]);

assert.that(numbers).is.not.containingAllOf([5]);
assert.that(numbers).is.not.containingAllOf([1, 5]);
assert.that(numbers).is.not.containingAllOf([1, 2, 5]);
```

### CODE REVIEW

**Comment by goloroden** [comment]
Hi @GaneshSPatil :-)

Just to make sure I get things right: The new function checks whether all of the expected values are contained within actual, but it would even be okay if it contained other elements, right?

So it basically is a subset check, isn't it?

Since I merged #19 before this one, there are now some conflicts. Would you mind resolving them?

**Comment by GaneshSPatil** [comment]
Hey @goloroden,
`containingAllOf` checks whether the all the elements of `expected` are present in `actual`.
`expected` need not contain all the elements of `actual`.
And `expected` can not contain any element which is not present in `actual`.

For Example:
```
assert.that([1, 2 3, 4]).is.containingAllOf([1]);
assert.that([1, 2 3, 4]).is.containingAllOf([1, 2]);
assert.that([1, 2 3, 4]).is.containingAllOf([1, 2, 3, 4]);

assert.that([1, 2 3, 4]).is.not.containingAllOf([1, 2, 5]);
```

**Comment by goloroden** [comment]
Okay, then I got it right. Thanks for the clarification :-)

And thanks for updating the PR that fast :-)

**Comment by goloroden** [comment]
And PS: Once again - really great work :-)

Thank you so much for submitting your ideas and code, and for taking the time to do all this! I really appreciate that!

A new version will be out in the next ~10 minutes.

**Pull request merged**
